CREATE TABLE Usuario(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	Telefono NUMERIC(18,0) NULL,
	PaisResidencia VARCHAR(100) NOT NULL,
	Contactar BIT NOT NULL
);

CREATE TABLE Actividad(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
	UsuarioId INT NOT NULL ,
	Actividad VARCHAR(200) NOT NULL
	CONSTRAINT FK_UsuarioActividad FOREIGN KEY (UsuarioId)
	REFERENCES dbo.Usuario(Id)
);

