// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BoomBitApi.Models
{
    public partial class Actividad
    {
        public int Id { get; set; }
        public DateTime FechaCreacion { get; set; }
        public int UsuarioId { get; set; }
        public string Actividad1 { get; set; }

        public virtual Usuario Usuario { get; set; }
    }
}