// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BoomBitApi.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            Actividads = new HashSet<Actividad>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public decimal? Telefono { get; set; }
        public string PaisResidencia { get; set; }
        public bool Contactar { get; set; }

        public virtual ICollection<Actividad> Actividads { get; set; }
    }
}