export const paises = [{id: 'AFG',text:' Afghanistan'},
{id: 'ALA',text:' Åland Islands'},
{id: 'ALB',text:' Albania'},
{id: 'DZA',text:' Algeria'},
{id: 'ASM',text:' American Samoa'},
{id: 'AND',text:' Andorra'},
{id: 'AGO',text:' Angola'},
{id: 'AIA',text:' Anguilla'},
{id: 'ATA',text:' Antarctica [a]'},
{id: 'ATG',text:' Antigua and Barbuda'},
{id: 'ARG',text:' Argentina'},
{id: 'ARM',text:' Armenia'},
{id: 'ABW',text:' Aruba'},
{id: 'AUS',text:' Australia [b]'},
{id: 'AUT',text:' Austria'},
{id: 'AZE',text:' Azerbaijan'},
{id: 'BHS',text:' Bahamas (the)'},
{id: 'BHR',text:' Bahrain'},
{id: 'BGD',text:' Bangladesh'},
{id: 'BRB',text:' Barbados'},
{id: 'BLR',text:' Belarus'},
{id: 'BEL',text:' Belgium'},
{id: 'BLZ',text:' Belize'},
{id: 'BEN',text:' Benin'},
{id: 'BMU',text:' Bermuda'},
{id: 'BTN',text:' Bhutan'},
{id: 'BOL',text:' Bolivia (Plurinational State of)'},
{id: 'BES',text:' Bonaire'},
{id: '',text:' Sint Eustatius'},
{id: '',text:' Saba'},
{id: 'BIH',text:' Bosnia and Herzegovina'},
{id: 'BWA',text:' Botswana'},
{id: 'BVT',text:' Bouvet Island'},
{id: 'BRA',text:' Brazil'},
{id: 'IOT',text:' British Indian Ocean Territory (the)'},
{id: '',text:' British Virgin Islands – See Virgin Islands (British).'},
{id: 'BRN',text:' Brunei Darussalam [e]'},
{id: 'BGR',text:' Bulgaria'},
{id: 'BFA',text:' Burkina Faso'},
{id: '',text:' Burma – See Myanmar.'},
{id: 'BDI',text:' Burundi'},
{id: 'CPV',text:' Cabo Verde [f]'},
{id: 'KHM',text:' Cambodia'},
{id: 'CMR',text:' Cameroon'},
{id: 'CAN',text:' Canada'},
{id: '',text:' Cape Verde – See Cabo Verde.'},
{id: '',text:' Caribbean Netherlands – See Bonaire, Sint Eustatius and Saba.'},
{id: 'CYM',text:' Cayman Islands (the)'},
{id: 'CAF',text:' Central African Republic (the)'},
{id: 'TCD',text:' Chad'},
{id: 'CHL',text:' Chile'},
{id: 'CHN',text:' China'},
{id: '',text:' China, The Republic of – See Taiwan (Province of China).'},
{id: 'CXR',text:' Christmas Island'},
{id: 'CCK',text:' Cocos (Keeling) Islands (the)'},
{id: 'COL',text:' Colombia'},
{id: 'COM',text:' Comoros (the)'},
{id: 'COD',text:' Congo (the Democratic Republic of the)'},
{id: 'COG',text:' Congo (the) [g]'},
{id: 'COK',text:' Cook Islands (the)'},
{id: 'CRI',text:' Costa Rica'},
{id: 'HRV',text:' Croatia'},
{id: 'CUB',text:' Cuba'},
{id: 'CUW',text:' Curaçao'},
{id: 'CYP',text:' Cyprus'},
{id: 'CZE',text:' Czechia [i]'},
{id: '',text:' Democratic Republic of the Congo – See Congo, The Democratic Republic of the.'},
{id: 'DNK',text:' Denmark'},
{id: 'DJI',text:' Djibouti'},
{id: 'DMA',text:' Dominica'},
{id: 'DOM',text:' Dominican Republic (the)'},
{id: '',text:' East Timor – See Timor-Leste.'},
{id: 'ECU',text:' Ecuador'},
{id: 'EGY',text:' Egypt'},
{id: 'SLV',text:' El Salvador'},
{id: 'GNQ',text:' Equatorial Guinea'},
{id: 'ERI',text:' Eritrea'},
{id: 'EST',text:' Estonia'},
{id: 'SWZ',text:' Eswatini [j]'},
{id: 'ETH',text:' Ethiopia'},
{id: 'FLK',text:' Falkland Islands (the) [Malvinas] [k]'},
{id: 'FRO',text:' Faroe Islands (the)'},
{id: 'FJI',text:' Fiji'},
{id: 'FIN',text:' Finland'},
{id: 'FRA',text:' France [l]'},
{id: 'GUF',text:' French Guiana'},
{id: 'PYF',text:' French Polynesia'},
{id: 'ATF',text:' French Southern Territories (the) [m]'},
{id: 'GAB',text:' Gabon'},
{id: 'GMB',text:' Gambia (the)'},
{id: 'GEO',text:' Georgia'},
{id: 'DEU',text:' Germany'},
{id: 'GHA',text:' Ghana'},
{id: 'GIB',text:' Gibraltar'},
{id: '',text:' Great Britain – See United Kingdom, The.'},
{id: 'GRC',text:' Greece'},
{id: 'GRL',text:' Greenland'},
{id: 'GRD',text:' Grenada'},
{id: 'GLP',text:' Guadeloupe'},
{id: 'GUM',text:' Guam'},
{id: 'GTM',text:' Guatemala'},
{id: 'GGY',text:' Guernsey'},
{id: 'GIN',text:' Guinea'},
{id: 'GNB',text:' Guinea-Bissau'},
{id: 'GUY',text:' Guyana'},
{id: 'HTI',text:' Haiti'},
{id: 'HMD',text:' Heard Island and McDonald Islands'},
{id: 'VAT',text:' Holy See (the) [n]'},
{id: 'HND',text:' Honduras'},
{id: 'HKG',text:' Hong Kong'},
{id: 'HUN',text:' Hungary'},
{id: 'ISL',text:' Iceland'},
{id: 'IND',text:' India'},
{id: 'IDN',text:' Indonesia'},
{id: 'IRN',text:' Iran (Islamic Republic of)'},
{id: 'IRQ',text:' Iraq'},
{id: 'IRL',text:' Ireland'},
{id: 'IMN',text:' Isle of Man'},
{id: 'ISR',text:' Israel'},
{id: 'ITA',text:' Italy'},
{id: 'JAM',text:' Jamaica'},
{id: '',text:' Jan Mayen – See Svalbard and Jan Mayen.'},
{id: 'JPN',text:' Japan'},
{id: 'JEY',text:' Jersey'},
{id: 'JOR',text:' Jordan'},
{id: 'KAZ',text:' Kazakhstan'},
{id: 'KEN',text:' Kenya'},
{id: 'KIR',text:' Kiribati'},
{id: 'KOR',text:' Korea (the Republic of) [p]'},
{id: 'KWT',text:' Kuwait'},
{id: 'KGZ',text:' Kyrgyzstan'},
{id: 'LVA',text:' Latvia'},
{id: 'LBN',text:' Lebanon'},
{id: 'LSO',text:' Lesotho'},
{id: 'LBR',text:' Liberia'},
{id: 'LBY',text:' Libya'},
{id: 'LIE',text:' Liechtenstein'},
{id: 'LTU',text:' Lithuania'},
{id: 'LUX',text:' Luxembourg'},
{id: 'MAC',text:' Macao [r]'},
{id: 'MKD',text:' North Macedonia [s]'},
{id: 'MDG',text:' Madagascar'},
{id: 'MWI',text:' Malawi'},
{id: 'MYS',text:' Malaysia'},
{id: 'MDV',text:' Maldives'},
{id: 'MLI',text:' Mali'},
{id: 'MLT',text:' Malta'},
{id: 'MHL',text:' Marshall Islands (the)'},
{id: 'MTQ',text:' Martinique'},
{id: 'MRT',text:' Mauritania'},
{id: 'MUS',text:' Mauritius'},
{id: 'MYT',text:' Mayotte'},
{id: 'MEX',text:' Mexico'},
{id: 'FSM',text:' Micronesia (Federated States of)'},
{id: 'MDA',text:' Moldova (the Republic of)'},
{id: 'MCO',text:' Monaco'},
{id: 'MNG',text:' Mongolia'},
{id: 'MNE',text:' Montenegro'},
{id: 'MSR',text:' Montserrat'},
{id: 'MAR',text:' Morocco'},
{id: 'MOZ',text:' Mozambique'},
{id: 'MMR',text:' Myanmar [t]'},
{id: 'NAM',text:' Namibia'},
{id: 'NRU',text:' Nauru'},
{id: 'NPL',text:' Nepal'},
{id: 'NLD',text:' Netherlands (the)'},
{id: 'NCL',text:' New Caledonia'},
{id: 'NZL',text:' New Zealand'},
{id: 'NIC',text:' Nicaragua'},
{id: 'NER',text:' Niger (the)'},
{id: 'NGA',text:' Nigeria'},
{id: 'NIU',text:' Niue'},
{id: 'NFK',text:' Norfolk Island'},
{id: 'MNP',text:' Northern Mariana Islands (the)'},
{id: 'NOR',text:' Norway'},
{id: 'OMN',text:' Oman'},
{id: 'PAK',text:' Pakistan'},
{id: 'PLW',text:' Palau'},
{id: 'PSE',text:' Palestine, State of'},
{id: 'PAN',text:' Panama'},
{id: 'PNG',text:' Papua New Guinea'},
{id: 'PRY',text:' Paraguay'},
{id: 'PER',text:' Peru'},
{id: 'PHL',text:' Philippines (the)'},
{id: 'PCN',text:' Pitcairn [u]'},
{id: 'POL',text:' Poland'},
{id: 'PRT',text:' Portugal'},
{id: 'PRI',text:' Puerto Rico'},
{id: 'QAT',text:' Qatar'},
{id: '',text:' Republic of China – See Taiwan (Province of China).'},
{id: '',text:' Republic of Korea – See Korea, The Republic of.'},
{id: '',text:' Republic of the Congo – See Congo, The.'},
{id: 'REU',text:' Réunion'},
{id: 'ROU',text:' Romania'},
{id: 'RUS',text:' Russian Federation (the) [v]'},
{id: 'RWA',text:' Rwanda'},
{id: '',text:' Saba – See Bonaire, Sint Eustatius and Saba.'},
{id: '',text:' Sahrawi Arab Democratic Republic – See Western Sahara.'},
{id: 'BLM',text:' Saint Barthélemy'},
{id: 'SHN',text:' Saint Helena'},
{id: '',text:' Ascension Island'},
{id: '',text:' Tristan da Cunha'},
{id: 'KNA',text:' Saint Kitts and Nevis'},
{id: 'LCA',text:' Saint Lucia'},
{id: 'MAF',text:' Saint Martin (French part)'},
{id: 'SPM',text:' Saint Pierre and Miquelon'},
{id: 'VCT',text:' Saint Vincent and the Grenadines'},
{id: 'WSM',text:' Samoa'},
{id: 'SMR',text:' San Marino'},
{id: 'STP',text:' Sao Tome and Principe'},
{id: 'SAU',text:' Saudi Arabia'},
{id: 'SEN',text:' Senegal'},
{id: 'SRB',text:' Serbia'},
{id: 'SYC',text:' Seychelles'},
{id: 'SLE',text:' Sierra Leone'},
{id: 'SGP',text:' Singapore'},
{id: '',text:' Sint Eustatius – See Bonaire, Sint Eustatius and Saba.'},
{id: 'SXM',text:' Sint Maarten (Dutch part)'},
{id: 'SVK',text:' Slovakia'},
{id: 'SVN',text:' Slovenia'},
{id: 'SLB',text:' Solomon Islands'},
{id: 'SOM',text:' Somalia'},
{id: 'ZAF',text:' South Africa'},
{id: 'SGS',text:' South Georgia and the South Sandwich Islands'},
{id: '',text:' South Korea – See Korea, The Republic of.'},
{id: 'SSD',text:' South Sudan'},
{id: 'ESP',text:' Spain'},
{id: 'LKA',text:' Sri Lanka'},
{id: 'SDN',text:' Sudan (the)'},
{id: 'SUR',text:' Suriname'},
{id: 'SJM',text:' Svalbard'},
{id: '',text:' Jan Mayen'},
{id: 'SWE',text:' Sweden'},
{id: 'CHE',text:' Switzerland'},
{id: 'SYR',text:' Syrian Arab Republic (the) [x]'},
{id: 'TWN',text:' Taiwan (Province of China) [y]'},
{id: 'TJK',text:' Tajikistan'},
{id: 'TZA',text:' Tanzania, the United Republic of'},
{id: 'THA',text:' Thailand'},
{id: 'TLS',text:' Timor-Leste [aa]'},
{id: 'TGO',text:' Togo'},
{id: 'TKL',text:' Tokelau'},
{id: 'TON',text:' Tonga'},
{id: 'TTO',text:' Trinidad and Tobago'},
{id: 'TUN',text:' Tunisia'},
{id: 'TUR',text:' Türkiye'},
{id: 'TKM',text:' Turkmenistan'},
{id: 'TCA',text:' Turks and Caicos Islands (the)'},
{id: 'TUV',text:' Tuvalu'},
{id: 'UGA',text:' Uganda'},
{id: 'UKR',text:' Ukraine'},
{id: 'ARE',text:' United Arab Emirates (the)'},
{id: 'GBR',text:' United Kingdom of Great Britain and Northern Ireland (the)'},
{id: 'UMI',text:' United States Minor Outlying Islands (the) [ac]'},
{id: 'USA',text:' United States of America (the)'},
{id: '',text:' United States Virgin Islands – See Virgin Islands (U.S.).'},
{id: 'URY',text:' Uruguay'},
{id: 'UZB',text:' Uzbekistan'},
{id: 'VUT',text:' Vanuatu'},
{id: '',text:' Vatican City – See Holy See, The.'},
{id: 'VEN',text:' Venezuela (Bolivarian Republic of)'},
{id: 'VNM',text:' Viet Nam [ae]'},
{id: 'VGB',text:' Virgin Islands (British) [af]'},
{id: 'VIR',text:' Virgin Islands (U.S.) [ag]'},
{id: 'WLF',text:' Wallis and Futuna'},
{id: 'ESH',text:' Western Sahara [ah]'},
{id: 'YEM',text:' Yemen'},
{id: 'ZMB',text:' Zambia'},
{id: 'ZWE',text:' Zimbabwe'}];